<h1>Sobre Nós</h1>
<hr/>

<?php foreach($this->view->dados as $indice => $info) { ?>

    <h1><?=$info['titulo']?></h1>;
    <br>
    <p><?=$info['descricao']?></p>';
    <hr>;


<?php }
?>

<?php
    
    /*foreach($this->view->dados as $indice => $info) {
        echo '<h1>'.$info['titulo'].'</h1>';
        echo '<br>';
        echo '<p>'.$info['descricao'].'</p>';
        echo '<hr>';
    }*/
?>